### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by iancustoica** [mikeage/prpltwtr#11]
Hello,

Is the prpltwtr plugin still supposed to work? I installed it on xubuntu 13.10 with stock pidgin (2.10.7)  and besides posting tweets I don't seem to be able to do anything else. Can anyone confirm this plugin is supposed to work on my distro and if yes maybe point me towards some documentation of how to use it? 

My home timeline is empty and not being updated even though there are tweets being posted by the people I follow on twitter. Also, there are 0 people in the room and I can't seem to perform any actions. 

The account disconnects randomly and all I can see as clues is "rate limited".

No buddies are added even though I checked the option to add people I follow as buddies...

Thank you for any info.

**Comment by tumpio** [comment]
Hi, I was wondering the same. Here is quote from README.md

> ### Version 0.13.0 (in progress)
> - Add Japanese translation
> - **Add support for Twitter API v1.1 (restore functionality)**
> - Fix Debian packaging

This plugin sounds very interesting and is something that I was looking for. How is the work on v1.1 API going on? Is it possible to restore? It is a shame that twitter is so hostile for 3rd party apps and plugins.

Thanks.

**Comment by mikeage** [comment]
Sorry, I missed this issue.

Timeline retrieval should be supported; make sure your refresh times are at least 2 minutes each. Just about everything should work (prpltwtr is my main twitter app); there's still an occasional crash on Windows I'm trying to investigate, but broadly speaking, it looks good.

If you have any specific problems, please open an issue and post a log; I'll try to make sure to notice it next time :)

**Comment by iancustoica** [comment]
Hi mikeage,

Well ok, thanks for the answer. My issue and my environment is described in my first post. Please let me know how to export the logs you need.

Thank you,
Iancu

**Comment by mikeage** [comment]
pidgin -d 2>&1 > pidgin.log should do it.

Also, make sure you're on the most recent version. There was an issue where the backfill used up almost all of the available API calls.

**Comment by tumpio** [comment]
I just tried it too, installed the version from here https://aur.archlinux.org/packages/prpltwtr/
0.12.0.r392-1 (development snapshot)

I have the same initial results as iancustoica posted in first post. Nothing is shown in my Home Timeline or "twitter list" "account/rss.

Search function did work, from Buddies > Add chat.. > account twitter and search term
It adds the group and shows the tweets/people on that chat room. Also every buddy was added from that group to own buddies group.

**Comment by tumpio** [comment]
^ops I just noticed that aur hostes different version from
https://github.com/dmoonfire/prpltwtr/

**Comment by iancustoica** [comment]
Here is a link to the log:

https://gist.github.com/iancustoica/3312002d0831e7da8639

**Comment by mikeage** [comment]
@dmoonfire did a LOT of work on getting this running, but the code there was not complete. 

Can you compile (or get whoever maintains https://aur.archlinux.org/packages/prpltwtr/ to compile) a newer version from this repository?

I know absolutely nothing about arch, but under debian/ubuntu, installing the pidgen-dev package is basically all that's required to build prpltwtr (the rest of the development packages are usually there; libglib, etc)

**Comment by tumpio** [comment]
Yep, I got it compiled and installed, but the Home Timeline and "@account/rss are still empty. No tweets nor people. But this time there is this message showing in the Home Timeline room:

> Conversation with Timeline: Home on Wed 05 Mar 2014 19:32:23 EET:
> (19:41:28) 
> The account has disconnected and you are no longer in this chat. You will automatically rejoin the chat when the account reconnects.

The account that I created was for the "Twitter protocol" from the account creation protocols drop down list. There is also "Status.net (Twitter Protocol)". Am I using the right one and what is the difference between the two?

**Comment by tumpio** [comment]
Here is new log file:
https://gist.github.com/tumpio/9373646

**Comment by mikeage** [comment]
Ignore the status protocol. It's no longer working.

Regarding your log:
(20:18:06) prpl-twitter: Response error: Error reading from api.twitter.com: response too long (524288 bytes limit)
(20:18:06) prpl-twitter: twitter_get_home_timeline_all_error_cb(0xe02680): Error reading from api.twitter.com: response too long (524288 bytes limit)
(20:18:06) prpl-twitter: post_failed called for account [REDACTED], error 1, message Error reading from api.twitter.com: response too long (524288 bytes limit)

I admit I've never seen this before. I'll look into it (it seems to be a libpurple thing), but in the meantime, can you try reducing the number of tweets to fetch from 200 to, say, 100?

**Comment by tumpio** [comment]
No difference for me, same errors as above again in the log.
I'm using the version 2.10.9 (libpurple 2.10.9) of Pidgin.

**Comment by mikeage** [comment]
Hmm... very interesting...

**Comment by heynnema** [comment]
My twitter feeds didn't show up until I double-clicked on "Home Timeline".

The api problem is that when you try to use it, it pops up and wants a password for api.twitter.com, but doesn't tell you that it's opened a browser window that contains the code required for the password/api.twitter.com dialog. Enter that number, and you're good to go.

Cheers, Al

**Comment by mikeage** [comment]
You can right click on the timeline (or any list / search) and choose "automatically open chat on new tweets". It's not the default, though I'm not sure why not :)

**Comment by Seanster** [comment]
Is there a windows x64 dll yet? I'd like to test it out maybe help debug. I am a programmer but I have no clue how to compile it for windows myself. If I had a few hints I would try. Can I simply cross-compile it on Linux?

**Comment by mikeage** [comment]
Slightly OT, but you can cross compile for windows (32 bit at least) with:

make -f Makefile.mingw PACKAGE_VERSION=0.13.0 PIDGIN_TREE_TOP=/path/to/sources/for/pidgin/ installer

Then copy prpltwtr-0.13.0.exe to your windows machine and install.

**Comment by bezirg** [comment]
I tried the latest version oif prpltwtr with Pidgin 2.10.9

My twitter list and DMs work fine.
What it does not work is the Home Timeline and list of following users.
- Home Timeline is empty and is not updated.
- Following users are not my actual following users, but the subset of users that have tweeted
  in my twitter list.

**Comment by tYGjQCsvVI** [comment]
Same issue here with the response being too long. This is with one tweet being retrieved.

`Error reading from api.twitter.com: response too long (524288 bytes limit)`

**Comment by mikeage** [comment]
You can try reducing the number of tweets being retrieved. Sadly, the pidgin functions I use for the REST queries are limited to 512KB, which is not enough for a full 200 tweets.

**Comment by KewlCat** [comment]
Hello

Modifying the number of tweets retrieved did not do anything for me. Whereas changing the call to purple_util_fetch_url_request_len_with_account() in src/prpltwtr/prpltwtr_request.c did.

 request_data->request_id = purple_util_fetch_url_request_len_with_account(account, full_url, TRUE, USER_AGENT, TRUE, request, TRUE, 1048576, twitter_send_request_cb, request_data);

There you go : no more "response too long".
I know it's ugly to override the defaults from libpurple but hey, it makes prpltwtr work !

HTH

**Comment by mikeage** [comment]
Huh... I could have sworn I tried that! 

Thanks! I'll merge it in a bit (I'm on mobile at the moment)
