### ISSUE TITLE
windows builds

### ISSUE THREAD

**Issue by c33s** [mikeage/prpltwtr#12]
it would be cool if you release nightly/pre/alpha/beta builds for windows.

**Comment by mikeage** [comment]
Yes, it would, but until github offers build machines, it's not feasible.

**Comment by c33s** [comment]
i ment, that you upload a windows binary somewhere. it would be more easy to test and to give you feedback if there where precomplied dlls to download somewhere.

**Comment by mikeage** [comment]
Done, btw, under the 'releases' tab.
