### ISSUE TITLE
Under Add Account>protocol there are two twiter items!??

### ISSUE THREAD

**Issue by FourthDr** [mikeage/prpltwtr#15]
After successfully building and installing the twitter plugin under Debian, I now have two twitter choices under add account>protocol. This is unexpected. Isn't there only suppose to be one choice? I can choose from the following two:

Status.net (twitter protocol)
twitter protocol

Is this the way it is suppose to be? Or has something gone horribly wrong? I was only expecting a single choice. Which one do I select when adding an account? And why are there two items instead of one? Please explain? Or have I found a bug/error?

**Comment by mikeage** [comment]
That's correct. Use the regular twitter one. Status.net is another site
(backend, really) using a similar API.

**Comment by FourthDr** [comment]
In what situation would you use status net for? First I have hear of it.

**Comment by mikeage** [comment]
If you have friends there.  The truth is that I no longer use it, but at
the time, it was just a few minutes work, because they based their API on
the twitter API.

**Comment by FourthDr** [comment]
Might want to put that in the plugin description. Might be a selling point for some people who use that site.

**Comment by mikeage** [comment]
OTOH, it's reported to be broken of late, but since I no longer use it, I don't know (or care all that much, to be honest). Yes, it'd "sell" better to remove it, but maybe another developer might want to fix it....

**Comment by FourthDr** [comment]
Now I have an oauth problem. When I enable twitter and try to add an account, the system default browser opens an http address instead of an https which is required by twitter. So I have to manually change the URL to make it https. I think this is a problem with your code when generating the oauth URL. The rest of the URL is correct.

Also, on my raspberry pi I only have two lightweight browsers available Midori and Dillo. Midori does not support https, and I can't logon to Twitter using Dillo. I can't run Firefox on the raspberry pi, not enough computing power. Have an alternate lightweight browser that will work that you can recommend? 

The plugin works file on a desktop with Xubuntu 14.04 LTS + Firefox. With the exception of the http URL being generated by the plugin instead of the required https. 

Next I will try building the windows version of the plugin...... ;-)

**Comment by mikeage** [comment]
Good find. I see Twitter changed this a while back, but as I don't
reauthorize very often, I never noticed. I'll push a fix tomorrow when I'm
back on my PC.

Personally, I use Windows for my desktop machines, so I can't offer any
thoughts about Linux browsers.

**Comment by mikeage** [comment]
Fixed in edcfe82d9a9a13cca3b834f0454ef27eb20b50f7
