### ISSUE TITLE
Won't update unless timeline window is open

### ISSUE THREAD

**Issue by heynnema** [mikeage/prpltwtr#16]
The individual tweets in the main Pidgin window only seem to populate, or update, if the main timeline window is open. Is this the intended behaviour? Is there a way for the user to change/recompile this such that the main Pidgin window updates with new tweets?

Please advise,

Al

**Comment by mikeage** [comment]
Right lick on the home timeline (or a list) in the buddy list and choose "Automatically open chat on new tweets"

**Comment by heynnema** [comment]
Thanks!
