### ISSUE TITLE
error in compilation

### ISSUE THREAD

**Issue by mama21mama** [mikeage/prpltwtr#2]
I fail to compile on debian 7.3

**Comment by mikeage** [comment]
Log please.

**Comment by mama21mama** [comment]
/bin/sed: can't read /usr/lib/libgstbase-0.10.la: No such file or directory
libtool: link: `/usr/lib/libgstbase-0.10.la' is not a valid libtool archive
make[3]: *** [libprpltwtr_twitter.la] Error 1
make[3]: se sale del directorio`/home/mama/Descargas/prpltwtr-twitter-json/src/prpltwtr'
make[2]: **\* [all-recursive] Error 1
make[2]: se sale del directorio `/home/mama/Descargas/prpltwtr-twitter-json/src'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio`/home/mama/Descargas/prpltwtr-twitter-json'
make: **\* [all] Error 2
[solved] http://blog.mamalibre.com.ar/post/solved-usrliblibgstbase-010la-not-valid-libtool-archive

/bin/sed: can't read /usr/lib/libgobject-2.0.la: No such file or directory
libtool: link: `/usr/lib/libgobject-2.0.la' is not a valid libtool archive
make[3]: *** [libprpltwtr_twitter.la] Error 1
make[3]: se sale del directorio`/home/mama/Descargas/prpltwtr-twitter-json/src/prpltwtr'
make[2]: **\* [all-recursive] Error 1
make[2]: se sale del directorio `/home/mama/Descargas/prpltwtr-twitter-json/src'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio`/home/mama/Descargas/prpltwtr-twitter-json'
make: **\* [all] Error 2

**Comment by mikeage** [comment]
Log please.

I don't know why prpltwtr should depend on gstreamer.

**Comment by mikeage** [comment]
Also, I see you complained about the same thing with a much earlier version of prpltwtr: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=714928

**Comment by mama21mama** [comment]
view /bin/sed: can't read /usr/lib/libgobject-2.0.la: No such file or directory

**Comment by mikeage** [comment]
gobject is a valid dependency, but I'd like to see a FULL LOG, containing ./configure and make.

Like the debian maintainer said, /usr/lib should not contain .la files at all; did you ever compile anything and put it there? You should have just .a and .so files in /usr/lib

It works for me for Ubuntu 12.04 and Ubuntu 13.10, so I'm assuming Debian 7.2 ought to be similar...

**Comment by mama21mama** [comment]
$bash autogen.sh 
**Message**: I am going to add --enable-maintainer-mode to `configure'.
If you wish to pass any other to it, please specify them on the
`autogen.sh' command line.

processing .
Creating ./aclocal.m4 ...
Running glib-gettextize...  Ignore non-fatal messages.
Copying file mkinstalldirs
Copying file po/Makefile.in.in

Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

Making ./aclocal.m4 writable ...
Running intltoolize...
Running libtoolize...
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file`./ltmain.sh'
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding`-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
Running aclocal  ...
Running autoheader...
Running automake --foreign  ...
Running autoconf ...
Running ./configure --enable-maintainer-mode ...
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking whether NLS is requested... yes
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.14.2
checking for XML::Parser... ok
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for catalogs to be installed...  es ja
checking pkg-config is at least version 0.15.0... yes
checking for PIDGIN... yes
checking for PIDGIN_DATADIR... /usr/share
checking for PIDGIN_PLUGINDIR... /usr/lib/pidgin
checking for PURPLE... yes
checking for PURPLE_DATADIR... /usr/share
checking for PURPLE_PLUGINDIR... /usr/lib/purple-2
checking for JSON... yes
checking for ANSI C header files... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for gethostname... yes
checking for inet_ntoa... yes
checking for memmove... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtoul... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating po/Makefile.in
config.status: creating data/Makefile
config.status: creating src/Makefile
config.status: creating src/prpltwtr/Makefile
config.status: creating src/gtkprpltwtr/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

prpltwtr 0.12.0

Pidgin plugin directory: /usr/lib/pidgin . Override by setting PIDGIN_PLUGINDIR
Pidgin data directory: /usr/share . Override by setting PIDGIN_DATADIR
libpurple plugin directory: /usr/lib/purple-2 . Override by setting PURPLE_PLUGINDIR

next steps:
make
sudo make install

Now type `make' to compile.

There was an error creating your comment: Body is too long (maximum is 65535 characters) XD

http://text0.tk/1458
http://text0.tk/1459

**Comment by mama21mama** [comment]
work https://twitter.com/mamalibre/status/413922161129451520

**Comment by mikeage** [comment]
I'm a bit confused; are you saying it works now (since you created a .deb)?

Can this be closed?

**Comment by mama21mama** [comment]
yes.  I had to add new files (*. la)

after that create a *. deb

**Comment by mikeage** [comment]
Where did you add them? Is it something you think is missing from my code? If so, please submit a pull request.

**Comment by mama21mama** [comment]
/usr/lib/libgobject-2.0.la
/usr/lib/libgmodule-2.0.la
/usr/lib/libxml2.la
/usr/lib/libidn.la
/usr/lib/libglib-2.0.la
/usr/lib/libgthread-2.0.la
http://bayresmail.com.ar/filebin/files/files-la.tar.bz2

**Comment by mikeage** [comment]
Where did you get these files from? 

It's strange that it needs these; it should be linking with /usr/lib/libgobject-2.0.a (or .so), etc, rather than the .la versions. Do you have these files (i.e., the same 6 files above but with .a and .so extensions instead of .la)? 

I don't see anything in the configure or make logs that explains why it's looking for these.

**Comment by mikeage** [comment]
Also, can you remove these .la files and try the following patch to configure.ac (you'll need to rerun autogen.sh)

diff --git i/configure.ac w/configure.ac
index 729f14f..427c959 100644
--- i/configure.ac
+++ w/configure.ac
@@ -72,6 +72,9 @@ AS_IF([test "x$with_pidgin" != xno],

 AM_CONDITIONAL([WITH_PIDGIN], [test "x$with_pidgin" != xno])

+PKG_CHECK_MODULES([GLIB], [glib-2.0])
+PKG_CHECK_MODULES([LIBXML2], [libxml-2.0])
+
 PKG_CHECK_MODULES([PURPLE], [purple],
                                  [
                                   AC_SUBST(PURPLE_CFLAGS)

**Comment by mama21mama** [comment]
them out of here:

http://stuff.mit.edu/afs/sipb/project/php/arch/sun/lib/libidn.la
http://stuff.mit.edu/afs/sipb/user/xiphmont/lib/libglib-2.0.la
http://web.mit.edu/barnowl/src/glib/glib-2.16.3/barnowl_locker_build/sun4x_510/gthread/libgthread-2.0.la
https://github.com/pfsense/pfsense-packages/blob/master/config/vhosts/freebsd7.2/usr.local.lib/libxml2.la
http://stuff.mit.edu/afs/sipb/project/gtk/gtk_v2.0/arch/sun4x_59/lib/libgmodule-2.0.la
http://stuff.mit.edu/afs/sipb/user/xiphmont/lib/libgobject-2.0.la

**Comment by mikeage** [comment]
Gotcha. Can you let me know (not necessarily now, obviously) if the patch fixes your problem (or at least leaves only one error for libidn; I'm not sure why that one is required)? I think my configure.ac script was actually missing these lines, and I just happened to get lucky and have the packages.

Do you have glib-dev and libxml2-dev installed?

**Comment by mama21mama** [comment]
libxml2-dev installed
glib-dev = libglib2.0-dev installed (debian 7.3)

I keep throwing same error. debian 7.3 with the patch included

uest.lo prpltwtr_search.lo prpltwtr_util.lo prpltwtr_xml.lo xmlnode_ext.lo -lglib-2.0   -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  
/bin/bash ../../libtool --silent --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..   -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include   -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/libpurple   -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include    -DLOCALEDIR=\"/usr/share/locale\"   -g -O2 -Wall -g3 -MT prpltwtr_plugin_twitter.lo -MD -MP -MF .deps/prpltwtr_plugin_twitter.Tpo -c -o prpltwtr_plugin_twitter.lo prpltwtr_plugin_twitter.c
mv -f .deps/prpltwtr_plugin_twitter.Tpo .deps/prpltwtr_plugin_twitter.Plo
/bin/bash ../../libtool --silent --tag=CC   --mode=link gcc  -g -O2 -Wall -g3 -module -avoid-version -lpurple -lglib-2.0   -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0    -o libprpltwtr_twitter.la -rpath /usr/lib/purple-2 prpltwtr_plugin_twitter.lo libprpltwtr.la 
/bin/sed: can't read /usr/lib/libgobject-2.0.la: No such file or directory
libtool: link: `/usr/lib/libgobject-2.0.la' is not a valid libtool archive
make[3]: *** [libprpltwtr_twitter.la] Error 1
make[3]: se sale del directorio`/home/mama/Descargas/prpltwtr-twitter-json/src/prpltwtr'
make[2]: **\* [all-recursive] Error 1
make[2]: se sale del directorio `/home/mama/Descargas/prpltwtr-twitter-json/src'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio`/home/mama/Descargas/prpltwtr-twitter-json'
make: **\* [all] Error 2
mama@zeuza:~/Descargas/prpltwtr-twitter-json$

**Comment by mikeage** [comment]
Interesting. I see no reason why it should be looking for the .la; I'll try to check if it's a known Debian issue. It certainly doesn't seem to be an issue with configure / makefile.

**Comment by mikeage** [comment]
A little bit of Googling suggests that sometimes one .la that shouldn't exist is what leads to the others. Can you try grepping for these .la files within the prpltwtr directory, and seeing why they're being used (instead of the .a / .so versions)

**Comment by shibotto** [comment]
> A little bit of Googling suggests that sometimes one .la that shouldn't exist is what leads to the others. Can you try grepping for these .la files within the prpltwtr directory, and seeing why they're being used (instead of the .a / .so versions)

@mikeage you saved me in a similar context with a totally unrelated project. If you are still reading this, thank you very much! :smiley:
