### ISSUE TITLE
libjson-glib-1.0 incompatability

### ISSUE THREAD

**Issue by c-h-u-c-k** [mikeage/prpltwtr#26]
How about compiling against the common libjson-glib-1.0.dll?
Thanks

**Comment by TomTheDragon** [comment]
It would be really nice because Pidgin dont seem to like it to have a libjson-glib-1.0.dll "and" a libjson-glib.dll loaded up.
It just crashes if you try to load plugins like the Skypeweb, Steam, Fchat or the Facebook plugin.

**Comment by intika** [comment]
i had the same issue... 
i just correct it on my fork... you can download compiled version here if you want 
https://github.com/intika/prpltwtr/tree/twitter-json/win_releases/current

i will pull request to correct the bug ;)
