### ISSUE TITLE
no work statusnet protocol

### ISSUE THREAD

**Issue by mama21mama** [mikeage/prpltwtr#7]
mama@zeuza:~/Descargas/prpltwtr-twitter-json$ pidgin -d -c  /home/mama/.purple/new
(04:01:25) prefs: Reading /home/mama/.purple/new/prefs.xml
(04:01:25) prefs: Finished reading /home/mama/.purple/new/prefs.xml
(04:01:25) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(04:01:25) dbus: okkk
(04:01:26) plugins: probing /usr/lib/pidgin/xmppconsole.so
(04:01:26) plugins: probing /usr/lib/pidgin/timestamp_format.so
(04:01:26) plugins: probing /usr/lib/pidgin/timestamp.so
(04:01:26) plugins: probing /usr/lib/pidgin/xmppdisco.so
(04:01:26) plugins: probing /usr/lib/pidgin/libgtkprpltwtr.so
(04:01:27) plugins: probing /usr/lib/pidgin/convcolors.so
(04:01:27) plugins: probing /usr/lib/pidgin/markerline.so
(04:01:27) plugins: probing /usr/lib/pidgin/ticker.so
(04:01:27) plugins: probing /usr/lib/pidgin/notify.so
(04:01:27) plugins: probing /usr/lib/pidgin/vvconfig.so
(04:01:27) plugins: probing /usr/lib/pidgin/gestures.so
(04:01:27) plugins: probing /usr/lib/pidgin/themeedit.so
(04:01:27) plugins: probing /usr/lib/pidgin/spellchk.so
(04:01:27) plugins: probing /usr/lib/pidgin/extplacement.so
(04:01:27) plugins: probing /usr/lib/pidgin/iconaway.so
(04:01:27) plugins: probing /usr/lib/pidgin/musicmessaging.so
(04:01:27) plugins: probing /usr/lib/pidgin/cap.so
(04:01:28) plugins: probing /usr/lib/pidgin/relnot.so
(04:01:28) plugins: probing /usr/lib/pidgin/gtkbuddynote.so
(04:01:28) plugins: probing /usr/lib/pidgin/pidginrc.so
(04:01:28) plugins: probing /usr/lib/pidgin/sendbutton.so
(04:01:28) plugins: probing /usr/lib/pidgin/history.so
(04:01:28) plugins: probing /usr/lib/purple-2/liboscar.so
(04:01:28) plugins: /usr/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(04:01:28) plugins: probing /usr/lib/purple-2/psychic.so
(04:01:28) plugins: probing /usr/lib/purple-2/libyahoojp.so
(04:01:28) plugins: probing /usr/lib/purple-2/libxmpp.so
(04:01:28) plugins: probing /usr/lib/purple-2/libymsg.so
(04:01:28) plugins: /usr/lib/purple-2/libymsg.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(04:01:28) plugins: probing /usr/lib/purple-2/idle.so
(04:01:28) plugins: probing /usr/lib/purple-2/libaim.so
(04:01:28) plugins: probing /usr/lib/purple-2/libwhatsapp.so
(04:01:28) plugins: probing /usr/lib/purple-2/newline.so
(04:01:28) plugins: probing /usr/lib/purple-2/libgg.so
(04:01:28) plugins: probing /usr/lib/purple-2/libmsn.so
(04:01:28) plugins: probing /usr/lib/purple-2/offlinemsg.so
(04:01:28) plugins: probing /usr/lib/purple-2/dbus-example.so
(04:01:28) plugins: probing /usr/lib/purple-2/libyahoo.so
(04:01:28) plugins: probing /usr/lib/purple-2/libmyspace.so
(04:01:28) plugins: probing /usr/lib/purple-2/libbonjour.so
(04:01:28) plugins: probing /usr/lib/purple-2/libjabber.so
(04:01:28) plugins: /usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(04:01:28) plugins: probing /usr/lib/purple-2/joinpart.so
(04:01:29) plugins: probing /usr/lib/purple-2/libprpltwtr.so
(04:01:29) plugins: /usr/lib/purple-2/libprpltwtr.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(04:01:29) plugins: probing /usr/lib/purple-2/ssl.so
(04:01:29) plugins: probing /usr/lib/purple-2/libmxit.so
(04:01:29) prpl-loubserp-mxit: Loading MXit libPurple plugin...
(04:01:29) plugins: probing /usr/lib/purple-2/libirc.so
(04:01:29) plugins: probing /usr/lib/purple-2/libzephyr.so
(04:01:29) plugins: probing /usr/lib/purple-2/perl.so
(04:01:29) plugins: probing /usr/lib/purple-2/autoaccept.so
(04:01:29) plugins: probing /usr/lib/purple-2/statenotify.so
(04:01:29) plugins: probing /usr/lib/purple-2/tcl.so
(04:01:29) plugins: probing /usr/lib/purple-2/libprpltwtr_twitter.so
(04:01:29) prpl-twitter: starting up
(04:01:29) plugins: probing /usr/lib/purple-2/buddynote.so
(04:01:29) plugins: probing /usr/lib/purple-2/ssl-nss.so
(04:01:30) plugins: probing /usr/lib/purple-2/log_reader.so
(04:01:30) plugins: probing /usr/lib/purple-2/libsametime.so
(04:01:30) plugins: /usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
(04:01:30) plugins: probing /usr/lib/purple-2/libnovell.so
(04:01:30) plugins: probing /usr/lib/purple-2/libsimple.so
(04:01:30) plugins: probing /usr/lib/purple-2/libprpltwtr_statusnet.so
(04:01:30) prpl-statusnet: starting up
(04:01:30) plugins: probing /usr/lib/purple-2/libicq.so
(04:01:30) util: Reading file xmpp-caps.xml from directory /home/mama/.purple/new
(04:01:30) util: File /home/mama/.purple/new/xmpp-caps.xml does not exist (this is not necessarily an error)
(04:01:30) jabber: creating hash tables for data objects
(04:01:30) prefs: /purple/status/scores/offline changed, scheduling save.
(04:01:30) prefs: /purple/status/scores/available changed, scheduling save.
(04:01:30) prefs: /purple/status/scores/invisible changed, scheduling save.
(04:01:30) prefs: /purple/status/scores/away changed, scheduling save.
(04:01:30) prefs: /purple/status/scores/extended_away changed, scheduling save.
(04:01:30) prefs: /purple/status/scores/idle changed, scheduling save.
(04:01:30) prefs: /purple/status/scores/offline_msg changed, scheduling save.
(04:01:30) util: Reading file accounts.xml from directory /home/mama/.purple/new
(04:01:30) util: Reading file status.xml from directory /home/mama/.purple/new
(04:01:30) certificate: CertificateVerifier x509, singleuse requested but not found.
(04:01:30) certificate: CertificateVerifier singleuse registered
(04:01:30) certificate: CertificatePool x509, ca requested but not found.
(04:01:30) certificate: CertificateScheme x509 requested but not found.
(04:01:30) certificate/x509/ca: Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.
(04:01:30) certificate/x509/ca: Init failed, probably because a dependency is not yet registered. It has been deferred to later.
(04:01:30) certificate: CertificatePool ca registered
(04:01:30) certificate: CertificatePool x509, tls_peers requested but not found.
(04:01:30) certificate: CertificatePool tls_peers registered
(04:01:30) certificate: CertificateVerifier x509, tls_cached requested but not found.
(04:01:30) certificate: CertificateVerifier tls_cached registered
(04:01:30) prefs: /purple/logging/format changed, scheduling save.
(04:01:30) prefs: /purple/logging/format changed, scheduling save.
(04:01:30) prefs: /purple/proxy/type changed, scheduling save.
(04:01:30) prefs: /purple/proxy/host changed, scheduling save.
(04:01:30) prefs: /purple/proxy/port changed, scheduling save.
(04:01:30) prefs: /purple/proxy/username changed, scheduling save.
(04:01:30) prefs: /purple/proxy/password changed, scheduling save.
(04:01:31) certificate: CertificateScheme x509 requested but not found.
(04:01:31) certificate: CertificateScheme x509 registered
(04:01:31) util: Reading file smileys.xml from directory /home/mama/.purple/new
(04:01:31) util: File /home/mama/.purple/new/smileys.xml does not exist (this is not necessarily an error)
(04:01:31) stun: using server 
(04:01:32) sound: Initializing sound output drivers.
(04:01:32) prefs: /pidgin/conversations/placement changed, scheduling save.
(04:01:32) prefs: purple_prefs_get_bool: Unknown pref /pidgin/docklet/x11/embedded
(04:01:32) GLib-GObject: /build/buildd-glib2.0_2.33.12+really2.32.4-5-i386-eISom6/glib2.0-2.33.12+really2.32.4/./gobject/gsignal.c:2459: signal `destroy' is invalid for instance`0xb8339988'
(04:01:32) gtkblist: added visibility manager: 1
(04:01:32) docklet: GTK+ created
(04:01:32) gtkmedia: Registering media element types
(04:01:35) util: Reading file blist.xml from directory /home/mama/.purple/new
(04:01:35) pounce: Error reading pounces: Falló al abrir el archivo «/home/mama/.purple/new/pounces.xml»: No existe el fichero o el directorio
(04:01:35) Session Management: No SESSION_MANAGER found, aborting.
(04:01:36) GLib-GObject: value "-1216740716" of type `gint' is invalid or out of range for property`weight' of type `gint'
(04:01:37) account: Connecting to account mamalibre.
(04:01:37) connection: Connecting. gc = 0xb8872108
(04:01:37) prpl-twitter: logging in mamalibre
(04:01:37) prpl-twitter: Sending GET request to: https://api.twitter.com/1.1/account/verify_credentials.json?oauth_callback=oob&oauth_consumer_key=9hDKG0Lty62lPca2XoA&oauth_nonce=1&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1387522897&oauth_token=91949860-pzXwcbKs42QYR9Ydmq2xl1BJcLvgu6tJuSFAVn7sC&oauth_signature=vON2kB3KoJyaNb%2BMVYDLNmPBS7g%3D
(04:01:37) util: requesting to fetch a URL
(04:01:37) dnsquery: Performing DNS lookup for api.twitter.com
(04:01:37) account: Connecting to account mama21mama@legadolibre.com.ar.
(04:01:37) connection: Connecting. gc = 0xb841b848
(04:01:37) prpl-statusnet: logging in mama21mama@legadolibre.com.ar
(04:01:37) prpl-statusnet: twitter_api_get_friends
(04:01:37) prpl-statusnet: Sending GET request to: https://legadolibre.com.ar/api/friends/ids(null)?screen_name=mama21mama%40legadolibre.com.ar&cursor=0
(04:01:37) util: requesting to fetch a URL
(04:01:37) dnsquery: Performing DNS lookup for legadolibre.com.ar
(04:01:37) util: Writing file prefs.xml to directory /home/mama/.purple/new
(04:01:37) util: Writing file /home/mama/.purple/new/prefs.xml
(04:01:37) util: Writing file accounts.xml to directory /home/mama/.purple/new
(04:01:37) util: Writing file /home/mama/.purple/new/accounts.xml
(04:01:37) dns: Created new DNS child 19652, there are now 1 children.
(04:01:37) dns: Successfully sent DNS request to child 19652
(04:01:37) dns: Created new DNS child 19653, there are now 2 children.
(04:01:37) dns: Successfully sent DNS request to child 19653
(04:01:37) docklet: embedded
(04:01:37) dns: Got response for 'api.twitter.com'
(04:01:37) dnsquery: IP resolved for api.twitter.com
(04:01:37) proxy: Attempting connection to 199.16.156.8
(04:01:37) proxy: Connecting to api.twitter.com:443 with no proxy
(04:01:37) proxy: Connection in progress
(04:01:37) dns: Got response for 'legadolibre.com.ar'
(04:01:37) dnsquery: IP resolved for legadolibre.com.ar
(04:01:37) proxy: Attempting connection to 190.19.160.189
(04:01:37) proxy: Connecting to legadolibre.com.ar:443 with no proxy
(04:01:37) proxy: Connection in progress
(04:01:37) proxy: Connecting to legadolibre.com.ar:443.
(04:01:37) proxy: Connected to legadolibre.com.ar:443.
(04:01:37) nss: subject=E=mama21mama@mamalibre.com.ar,CN=legadolibre.com.ar,O=MamaLibre,L=Lincoln,ST=Buenos Aires,C=AR issuer=E=mama21mama@mamalibre.com.ar,CN=legadolibre.com.ar,O=MamaLibre,L=Lincoln,ST=Buenos Aires,C=AR
(04:01:37) certificate/x509/tls_cached: Starting verify for legadolibre.com.ar
(04:01:37) certificate/x509/tls_cached: Checking for cached cert...
(04:01:37) certificate/x509/tls_cached: ...Found cached cert
(04:01:37) nss/x509: Loading certificate from /home/mama/.purple/new/certificates/x509/tls_peers/legadolibre.com.ar
(04:01:37) certificate/x509/tls_cached: Peer cert matched cached
(04:01:37) nss/x509: Exporting certificate to /home/mama/.purple/new/certificates/x509/tls_peers/legadolibre.com.ar
(04:01:37) util: Writing file /home/mama/.purple/new/certificates/x509/tls_peers/legadolibre.com.ar
(04:01:37) certificate: Successfully verified certificate for legadolibre.com.ar
(04:01:37) util: request constructed
(04:01:37) proxy: Connecting to api.twitter.com:443.
(04:01:37) proxy: Connected to api.twitter.com:443.
(04:01:38) util: Response headers: 'HTTP/1.0 404 Not Found
Expires: Fri, 03 Jan 2014 07:01:37 GMT
Cache-Control: max-age=1209600
Content-Type: text/html; charset=utf-8
Connection: close
Date: Fri, 20 Dec 2013 07:01:37 GMT
Server: lighttpd/1.4.31

'
Pidgin 2.10.6 ha tenido un fallo y ha intentado generar un archivo «core».
Esto es una errata en el programa y no se ha producido por
algo que haya hecho.

Si puede reproducir este fallo, por favor, notifíquelo a los 
desarrolladores de Pidgin enviando un informe de errata a
http://developer.pidgin.im/simpleticket/

Asegúrese de especificar lo que estaba haciendo en el momento de
suceder esto y envíenos su traza del archivo «core». Si no sabe como
obtener una traza consulte las instrucciones disponibles en
http://developer.pidgin.im/wiki/GetABacktrace
dns[19653]: Oops, father has gone, wait for me, wait...!
dns[19652]: Oops, father has gone, wait for me, wait...!
Abortado

**Comment by mikeage** [comment]
I'm not surprised; I know some of the changes we made for twitter broke status.net. I'll try to get to this, but it might take a while.

**Comment by mama21mama** [comment]
good luck. Shame more statusnet use the old twitter
