### ISSUE TITLE
App.net support

### ISSUE THREAD

**Issue by t3mujin** [mikeage/prpltwtr#8]
I honestly haven't looked deeply into App.net's API and don't know if it's easily integrated into prpltwtr, so I add this as a feature request to be considered for the roadmap.

**Comment by mikeage** [comment]
This is the first time I've ever heard of app.net; the API is slightly similar, but not all that close. I can't imagine I'll ever do this, but if someone wants to fork this code and use it as a basis for app.net support... best of luck to them.

Sorry.
