### ISSUE TITLE
prpltwtr:// links in twitter messages

### ISSUE THREAD

**Issue by slmingol** [mikeage/prpltwtr#9]
I asked this Q in this thread originally: http://code.google.com/p/prpltwtr/issues/detail?id=88

> When the Home Timeline shows up, each tweet shows an annoying prpltwtr:///actions?account=.... at the end. Can I disable this?

To which I got this answer:

> Regarding the prpltwtr:// link, you might want to consider enabling the gtkprpltwtr plugin; it gives you a LOT of nice options (reply, reply-all, favorite, RT, mark as spam) that are possible with a GUI client like pidgin. It should have been enabled by default, but there was an earlier version (post the twitter-json branch) that didn't load, and that might have blocked it from retrying the auto enable.

To my knowledge the gtkprpltwtr plugin is enabled however I'm not seeing the extra options mentioned, or perhaps I'm not looking in the correct location. Any help/guidance would be appreciated.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://f.cloud.github.com/assets/15072/1797205/2a564eac-6abc-11e3-99ad-db54bd739016.png)

**Comment by mikeage** [comment]
Strange; that plugin should convert the prpltwtr:// link into a hyperlinked \* at the end of each tweet.

**Comment by slmingol** [comment]
When the window automatically pops up the prpltwtr:// links are expanded out. However when I close the Home Timeline window and reopen it, the link is hidden as you're describing.

_example popup window_

![image](https://f.cloud.github.com/assets/15072/1797215/cb86f4f0-6abe-11e3-97ce-c56d20ca43fa.png)

_example reopened window_

![image](https://f.cloud.github.com/assets/15072/1797216/d98f8cce-6abe-11e3-8ec3-e7b4bec5db46.png)

**Comment by mikeage** [comment]
Do you have any other plugins that could be doing this? The re-opened window seems to be showing the history (note that it also doesn't have the picture or the coloring).

**Comment by slmingol** [comment]
Yes, I have a dozen or so other plugins enabled. I'll go through and disable them all to start and see which one is potentially interfering with this one.

**Comment by mikeage** [comment]
Thanks. See also https://code.google.com/p/prpltwtr/issues/detail?id=53 .
